### ISSUE TITLE
Charm 2.3.2 crash with Optifabric

### ISSUE THREAD

**Issue by Chucky2401** [svenhjol/Charm#518] opened 2021-03-27 12:16 UTC
Read me first!
1. Is your issue about the Forge version of Charm? Please report your issue here: https://github.com/svenhjol/CharmForge/issues
2. We don't support OptiFabric! Please check that the problem still occurs if you remove OptiFabric from your mods.
3. Don't use the bug report to suggest new features or behavior.

Versions
* Charm version: `2.3.2`
* Minecraft version: `1.6.5`
* Fabric Loader: `0.11.3`
* Fabric API: `0.32.5+1.16.5`
* Optifabric: `1.9.6`
* Optifine: `1.16.5_HD_U_G7`

Description
The game crash at start

Steps To Reproduce
Just launch the game

Stacktrace/Screenshots
I use MultiMC and when I disabled Optifabric the game run without any issues
Here a link to the log : https://pastebin.com/GMMxdUcN

**Comment by RDKRACZ** [comment] 2021-03-27 12:32
😂 The "Read me first!" section is only 3 lines and even this is too long for you.

@svenhjol please add "breaks" or "conflicts" to the dependency resolution in the fabric.mod.json file because you explicitly stated that optifabric is not supported.

**Comment by RDKRACZ** [comment] 2021-03-27 12:36
@Chucky2401 duplicate of https://github.com/svenhjol/Charm/issues/503, https://github.com/svenhjol/Charm/issues/335 and many others. Close this.

**Comment by Chucky2401** [comment] 2021-03-27 12:59
I read it, if I post this issue it's because it worked with an Minecraft 1.16.4, with OptiFabric.
I don't understand, something change between these two versions?

**Comment by svenhjol** [comment] 2021-03-27 17:49
Thanks @RDKRACZ I'll add this to fabric.mod.json

**Closed by svenhjol** 2021-03-27 17:49 UTC
