### ISSUE TITLE
Crashed problem with quark installed

### ISSUE THREAD

**Issue by HonestAngel** [svenhjol/Charm#424] opened 2020-12-16 01:27 UTC
Charm-forge-1.16.4-2.1.6
minecraft 1.16.4
Forge 1.16.4-forge-35.1.13

-- MOD charm --
Details:
	Caused by 0: java.lang.NoClassDefFoundError: vazkii/quark/world/gen/structure/BigDungeonStructure

[crash-2020-12-15_17.22.09-fml.txt](https://github.com/svenhjol/Charm/files/5699711/crash-2020-12-15_17.22.09-fml.txt)

**Comment by HonestAngel** [comment] 2020-12-16 01:28
forgot to add Quark-r2.4-280

**Comment by thepriz** [comment] 2020-12-16 02:22
I can confirm this is happening with the latest version of Quark-r2.4.280 installed.

**Comment by FesterHead** [comment] 2020-12-16 03:38
Looks like folders have been re-arranged in Quark-r2.4-280.jar

**Comment by CynicalShrew** [comment] 2020-12-17 01:50
Same here. Opened an issue on the Quark Github and got this reply.

"This needs to be fixed on charm's end. I moved the file to a different package and it's still looking for the old one."
_Originally posted by @Vazkii in https://github.com/Vazkii/Quark/issues/2731#issuecomment-747064885_

Here's the crash log I posted for it: https://pastebin.com/mCrnzVX6

**Comment by svenhjol** [comment] 2020-12-17 01:51
Fix is being worked on.

**Comment by svenhjol** [comment] 2020-12-17 02:28
Fixed version:
* github: https://github.com/svenhjol/Charm/releases/download/2.1.9/charm-forge-1.16.4-2.1.9.jar
* curseforge: https://www.curseforge.com/minecraft/mc-mods/charm/files/3140950

**Comment by FesterHead** [comment] 2020-12-17 03:23
charm-forge-1.16.4-2.1.9.jar resolves this issue.
thank you

**Closed** 2020-12-19 01:59 UTC
