### ISSUE TITLE
Crate UI persists after breaking when one player has the UI open and the other breaks the crate. Done with 2 players, can be used to duplicrate items

### ISSUE THREAD

**Issue by daddybing** [svenhjol/Charm#214] opened 2020-01-16 05:37 UTC

**Comment by svenhjol** [comment] 2020-02-08 22:10
Duplicrate :)
What version of Charm is this happening in?

**Comment by daddybing** [comment] 2020-02-09 22:06
> Duplicrate :)
> What version of Charm is this happening in?

Charm-1.12.2-1.3.6

**Comment by svenhjol** [comment] 2020-04-19 20:12
Duplicate of #178, will be fixed in next 1.12 version

**Comment by svenhjol** [comment] 2020-04-19 21:55
Should be fixed in latest version:
https://www.curseforge.com/minecraft/mc-mods/charm/files/2934951

**Closed by svenhjol** 2020-04-19 21:55 UTC
Labels: 1.12, bug, duplicate
