### ISSUE TITLE
Charm Crash on common_setup phase related to quark BigDungeonStructure

### ISSUE THREAD

**Issue by Ragotha** [svenhjol/Charm#436] opened 2020-12-21 02:43 UTC
Charm version - 2.1.6
Minecraft version - 1.6.4
Loader - Forge

Description
Crash on Startup

Optional: Stacktrace/Screenshots
https://pastebin.com/yPjGydzc

**Comment by F43nd1r** [comment] 2020-12-21 02:47
Duplicate of #424

**Closed** 2020-12-21 02:47 UTC

**Comment by Ragotha** [comment] 2020-12-21 02:56
my bad, didn't spot that.
