### ISSUE TITLE
Mod menu support

### ISSUE THREAD

**Issue by SylisMC** [svenhjol/Charm#474] opened 2021-01-10 16:18 UTC
[Mod menu](https://www.curseforge.com/minecraft/mc-mods/modmenu) is really awesome for changing config files on the go, and it cuts out the restart the game process when building a modpack. support for it would be genuinely awesome

**Comment by F43nd1r** [comment] 2021-01-10 16:30
Duplicate of #452

**Closed by F43nd1r** 2021-01-10 16:30 UTC
