### ISSUE TITLE
Inventory disappears from chest boat in 1.19

### ISSUE THREAD

**Issue by shaffera777** [svenhjol/Charm#800] opened 2022-06-19 19:49 UTC
The inventory in the chest boat disappears if you quit the game.

**Comment by Inurosen** [comment] 2022-06-26 18:05
I can confirm this. My rare loot gone now. :(

**Comment by wise-io** [comment] 2022-07-11 19:24
Can confirm on `Charm 4.1.2`. 

**Tested with the following mods:**
```
Fabric API 0.56.3
Charm 4.1.2
```
I also tested with `Fabric API 0.57.0`.

**Steps to reproduce:**
```
1. Put any item in boat chest.
2. Logout of world.
3. Login to world.
4. Check for items in boat chest.
```

**Comment by Inurosen** [comment] 2022-08-06 18:33
Charm 4.2.0
Still not fixed. Frustrating.

**Comment by HelpComputr** [comment] 2022-08-06 19:31
Yeah, boat chests are still broken on the latest update.

**Comment by WarlordWossman** [comment] 2022-08-07 04:24
@Inurosen @HelpComputr should be fixed in 4.2.1 from what we could test so far! Let us know if that holds true.

**Comment by Inurosen** [comment] 2022-08-07 07:03
I can confirm this bug is fixed now. Many thanks!

**Comment by WarlordWossman** [comment] 2022-08-07 07:20
> I can confirm this bug is fixed now. Many thanks!

thanks to everybody reporting and commenting/confirming bugs, this one def went under the radar because it was reported when everybody was busy - gotta work through some other issues when there is time

**Closed by WarlordWossman** 2022-08-07 07:20 UTC
Labels: bug
