### ISSUE TITLE
Minecraft gave me when the game was loading up.

### ISSUE THREAD

**Issue by Niconoko** [svenhjol/Charm#465] opened 2021-01-02 09:47 UTC
https://pastebin.com/upiVStyu
Not sure what's going on, here's a crash log.

**Comment by wolperite** [comment] 2021-01-02 12:49
i have something similar https://pastebin.com/8qXJDwES , it appears to be an issue with one of quarks worldgen
Exception message: java.lang.ClassNotFoundException: vazkii.quark.world.gen.structure.BigDungeonStructure

**Comment by SoldierKucha** [comment] 2021-01-04 07:45
Same https://pastebin.com/t3Z4x2Rz

**Comment by ridjack** [comment] 2021-01-08 17:25
Duplicate of svenhjol/Charm#25 .

**Closed by ridjack** 2021-01-08 17:25 UTC
