### ISSUE TITLE
CoralSquids spawn in way too high quantities

### ISSUE THREAD

**Issue by elFlashor** [svenhjol/Charm#443] opened 2020-12-24 11:22 UTC
**Read me first!**
1. We don't support Optifine or Optifabric. Please check that the problem still occurs if you remove Optifine/Optifabric from your mods.
2. Don't use the bug report to suggest new features or behavior.

**Required - Versions**
* Charm version - charm-forge-1.16.4-2.1.1-hotfix3
* Minecraft version - 1.16.3
* Loader - Forge

**Required - Description**
Sudden FPS drop to 1 upon coming close to a coral ocean. The tick process used 97% or my ressources while it was happening. Lowering the render distance to 2 chunks allowed me to see a huge quantity or small coral squids spawned in the ocean (100s of them!). Killing them all with a command suddenly made my FPS back to normal.

**Optional: Steps To Reproduce**
Didn't seem to happen another time so far, but I guess just come close to a coral ocean and hope the issue will happen?

**Optional: Stacktrace/Screenshots**

**Comment by F43nd1r** [comment] 2020-12-24 12:19
Duplicate of #375 
Update charm.

**Closed by F43nd1r** 2020-12-24 12:19 UTC
